import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Our products',
  description: 'Generated by create next app',
};

export default function OurProductsLayout({
  children,
  products,
  contacts,
}: Readonly<{
  children: React.ReactNode;
  products: React.ReactNode;
  contacts: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        {children}
        <div className='grid grid-cols-1 md:grid-cols-2 m-6'>
          {products} {contacts}
        </div>
      </body>
    </html>
  );
}
